#!/bin/sh
app_dir=$(cd $(dirname "$0") && pwd)
#cd "${app_dir}"
if [ "$#" -eq 0 ]; then
	programname=`basename "$0"`
	echo "ERROR: No program supplied"
	echo
	echo "Usage: $programname <program>"
	exit 1
fi

if [ "$1" = "--dlsym" ]; then
	MANGOHUD_DLSYM=1
	shift
fi

MANGOHUD_LIB_NAME="libMangoHud.so"

if [ "$MANGOHUD_DLSYM" = "1" ]; then
	MANGOHUD_LIB_NAME="libMangoHud_dlsym.so:${MANGOHUD_LIB_NAME}"
fi

# Preload using the plain filenames of the libs, the dynamic linker will
# figure out whether the 32 or 64 bit version should be used, and will search
# for it in the correct directory
LD_PRELOAD="${MANGOHUD_LIB_NAME}"
LD_LIBRARY_PATH="${app_dir}"

exec env MANGOHUD=1 VK_LAYER_PATH="${app_dir}" VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" LD_PRELOAD="${LD_PRELOAD}" "$@"
